version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./storage:/var/lib/clickhouse
    networks:
      - clickhouse_net

networks:
  clickhouse_net:
    driver: bridge